import type { Metadata } from "next";
import "./globals.css";
import { SessionProvider } from "@/SessionProvider";
import { Toaster } from "@/components/ui/toaster";
import TokenHandler from "@/components/TokenHandler";
import { SidebarProvider } from "@/components/ui/sidebar";

export const metadata: Metadata = {
  title: "Social Media",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <SidebarProvider>
            <TokenHandler />
            {children}
            <Toaster />
          </SidebarProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
